language: go

go:
  - "1.6.x"  # ubuntu 16.04
  - "1.7.x"  # debian stable
  - "1.10.x" # ubuntu 18.04
  - "1.x"    # latest release

install:
  - go get -u golang.org/x/lint/golint || true
  - make deps

script:
  - make check
  - make
  - make test
  - make install
  - make uninstall
